config/routes.rb
Rails.application.routes.draw do
  post 'pusher/auth'

  resources :projectideas
  post "/projectideas/like/:id" => "projectideas#like"
  post "/projectideas/unlike/:id" => "projectideas#unlike"
  post '/projectideas/:id/comments/create' => "projectideas#comment_create"

  devise_for :developers
  devise_for :creatives

  unauthenticated do
    root "site#home"
  end
 
  authenticated do 
  	root "site#dashboard", as: :authenticated_root
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :projectidea
	belongs_to :creative
	belongs_to :developer
	after_create :show_comment

	def show_comment
		puts "\n\n\n\n\n", self
	end


	def with_author
		
	end
end

app/models/creative.rb
class Creative < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :comments
         acts_as_voter
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :comments
         acts_as_voter 

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/project_idea.rb
class ProjectIdea < ActiveRecord::Base
  include ActiveModel::Serialization
  belongs_to :creative
  has_many :comments
  acts_as_votable
 
  def self.page_count
  	(ProjectIdea.count / 20.0).ceil + 1 
  end

  def self.get_with_likes(page_number)
  	self.includes(:votes_for).page(page_number).per(10)
  end

  def self.get_serialized_with_likes_and_comments(user, page_number)
  	project_list = ProjectIdea
  						.includes(:votes_for)
  						.includes(:comments)
  						.page(page_number)
  						.per(10)

  	serialized_list = project_list.map do | project |
  	   {
  		  project: project,
  		  likes: project.votes_for.count,
  		  comments: project.comments.to_a,
  		  liked: user.voted_for?(project)
  		}.as_json
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	current_developer || current_creative
  end

end

app/controllers/projectideas_controller.rb
class ProjectideasController < ApplicationController
	
	def index
		@projects = ProjectIdea.get_serialized_with_likes_and_comments(current_user, params[:page])

		render json: {
					  projects:   @projects, 
					  page_count: ProjectIdea.page_count
					}
	end

	def comment_create
		@project = ProjectIdea.find_by_id(params[:id])
		if current_creative
			@comment = @project.comments.new(creative_id: current_creative.id, comment_text: params[:text])
		else
			@comment = @project.comments.new(developer_id: current_developer.id, comment_text: params[:text])
		end
		@comment.save!
		Pusher.trigger("ProjectIdeas", "new_comment", {message: {project_id: @project.id, comment: @comment}})
		render json: nil, status: :ok
	end

	def like
		@project_idea = ProjectIdea.find_by_id(params[:id])
		@project_idea.liked_by(current_user)
		Pusher.trigger('ProjectIdeas', 'liked', {message: {project_id: @project_idea.id, votes_for: @project_idea.votes_for.count}})
		render :nothing => true
	end

	def unlike
		@project_idea = ProjectIdea.find_by_id(params[:id])
		@project_idea.unliked_by(current_user)
		Pusher.trigger('ProjectIdeas', 'unliked', {message: {project_id: @project_idea.id, votes_for: @project_idea.votes_for.count}})
		render :nothing => true
	end
end

app/controllers/pusher_controller.rb
class PusherController < ApplicationController
	protect_from_forgery :except => :auth # stop rails CSRF protection for this action

	def auth
	  if current_user
	    response = Pusher[params[:channel_name]].authenticate(params[:socket_id])
	    render :json => response
	  else
	    render :text => "Not authorized", :status => '403'
	  end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	protected 

	def after_sign_in_path_for(resource)
	    dashboard_path
	end
end	

app/controllers/site_controller.rb
class SiteController < ApplicationController

  before_action :authenticate_creative!, :except => [:home]
  before_action :authenticate_developer!, :except => [:home]


  def home
  end

  def dashboard
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projectideas_helper.rb
module ProjectideasHelper
end

app/helpers/pusher_helper.rb
module PusherHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/creatives/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/developers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SomebodyMakeThis</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="http://js.pusher.com/3.0/pusher.min.js"></script>
  <script>
      // Enable pusher logging - don't include this in production
      Pusher.log = function(message) {
        if (window.console && window.console.log) {
          window.console.log(message);
        }
      };

      var pusher = new Pusher('9f9ed06cce5bf67a02c2', {
        encrypted: true
      });
    </script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pusher/auth.html.erb
<h1>Pusher#auth</h1>
<p>Find me in app/views/pusher/auth.html.erb</p>

app/views/site/dashboard.html.erb
 <div class="row project_body">
    <div class="col-sm-12">
         <div class="panel panel-default panel-story">
         <div class="panel-heading text-center"><h2>Top Project Ideas</h2></div>
         <div class="panel-body comment-box text-center">
         	<%= react_component 'ProjectIdeaTable' %>
          </div>
         </div>
 	</div>
   </div>
</div>

app/views/site/home.html.erb
<!-- <div class="navbar navbar-fixed-top navbar-bold" data-spy="affix" data-offset-top="1000">
  <div class="container">
    <div class="navbar-header">
      <a href="#" class="navbar-brand">Home</a>
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav">
        <li><a href="#sec1">Section 1</a></li>
        <li><a href="#sec2">Section 2</a></li>
        <li><a href="#sec3">Section 3</a></li>
        <li><a href="#sec4">Section 4</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><a href="#sec2">Hey</a></li>
      </ul>
    </div>
   </div>
</div>
 -->

  
<div class="blurb bright">
  
  <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Get Started</h1>
        <br>
      </div>
  </div>

 <div class="row">
    <div class="col-sm-6 ">
         <div class="panel panel-default">
         <div class="panel-heading text-center"><h2><i class="icon-chevron-left"></i> Creatives</h2></div>
         <div class="panel-body text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate. 
          Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis 
          dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan. 
          Aliquam in felis sit amet augue.<hr>
          <%= button_to 'Sign Up', new_creative_registration_path, class: "btn btn-lg btn-primary btn-block", method: "get" %>
          </div>
         </div>
 	</div>
    <div class="col-sm-6">
         <div class="panel panel-default">
         <div class="panel-heading text-center"><h2>Developers<i class="icon-chevron-right"></i></h2></div>
         <div class="panel-body text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra varius quam sit amet vulputate. 
          Quisque mauris augue, molestie tincidunt condimentum vitae, gravida a libero. Aenean sit amet felis 
          dolor, in sagittis nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor accumsan. 
          Aliquam in felis sit amet augue.<hr>
            <%= button_to 'Sign Up', new_developer_registration_path, class: "btn btn-lg btn-primary btn-block", method: "get" %>
          </div>
         </div>
 	</div>
  </div>
</div>
  <!-- <div class="container"> -->
 
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <ul class="list-inline">
          <li><i class="icon-facebook icon-2x"></i></li>
          <li><i class="icon-twitter icon-2x"></i></li>
          <li><i class="icon-google-plus icon-2x"></i></li>
          <li><i class="icon-pinterest icon-2x"></i></li>
        </ul>
        <hr>
        <br>Company ©2013
      </div>
    </div>
  </div>
</footer>

<ul class="nav pull-right scroll-down">
  <li><a href="#" title="Scroll down"><i class="icon-chevron-down icon-3x"></i></a></li>
</ul>
<ul class="nav pull-right scroll-top">
  <li><a href="#" title="Scroll to top"><i class="icon-chevron-up icon-3x"></i></a></li>
</ul>

	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/scripts.js"></script>
	</body>
</html>